[2024-09-30 10:34:35,235.235] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:34:37,797.797] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:34:37,799.799] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:38:16,682.682] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:38:16,968.968] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:38:19,367.367] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:38:19,370.370] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:39:19,082.082] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:39:19,340.340] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:39:22,001.001] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:39:22,004.004] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:39:26,909.909] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:39:27,162.162] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:39:29,538.538] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:39:29,541.541] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:39:48,126.126] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:39:48,382.382] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:39:50,868.868] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:39:50,871.871] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:39:54,540.540] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:39:54,774.774] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:39:56,910.910] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:39:56,913.913] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:40:01,783.783] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:40:02,035.035] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:40:04,225.225] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:40:04,227.227] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:40:30,462.462] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:40:30,715.715] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:40:33,134.134] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:40:33,138.138] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:41:20,329.329] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:41:20,562.562] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:41:22,994.994] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:41:22,997.997] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:41:34,772.772] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:41:35,016.016] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:41:37,510.510] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:41:37,512.512] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:41:41,207.207] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:41:41,465.465] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:41:43,945.945] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:41:43,946.946] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:41:46,444.444] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:41:46,707.707] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:41:48,878.878] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:41:48,878.878] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:41:52,424.424] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:41:52,679.679] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:41:54,851.851] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:41:54,852.852] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:41:57,211.211] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:41:57,449.449] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:41:59,666.666] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:41:59,668.668] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:42:05,309.309] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:42:05,617.617] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:42:07,882.882] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:42:07,883.883] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:42:15,648.648] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:42:15,902.902] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:42:18,080.080] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:42:18,081.081] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:42:20,430.430] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:42:20,671.671] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:42:22,849.849] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:42:22,851.851] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:43:02,968.968] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\命名空间.py', reloading
[2024-09-30 10:43:03,237.237] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:43:05,484.484] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:43:05,486.486] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:43:16,555.555] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:43:16,879.879] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:43:19,353.353] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:43:19,355.355] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:44:03,038.038] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:44:03,312.312] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:44:05,768.768] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:44:05,770.770] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:44:07,159.159] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:44:07,433.433] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:44:09,675.675] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:44:09,677.677] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:44:12,052.052] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:44:12,293.293] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:44:14,526.526] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:44:14,527.527] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:44:17,939.939] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:44:18,171.171] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:44:20,745.745] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:44:20,746.746] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:44:22,030.030] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:44:22,266.266] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:44:24,468.468] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:44:24,469.469] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:44:55,449.449] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:44:55,696.696] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:44:57,866.866] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:44:57,868.868] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:45:18,714.714] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:45:18,964.964] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:45:21,074.074] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:45:21,075.075] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:45:48,487.487] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:45:48,744.744] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:45:50,918.918] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:45:50,920.920] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:46:11,728.728] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 10:46:11,966.966] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:46:14,299.299] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:46:14,302.302] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:46:40,434.434] _internal.py -> _log line:96 [INFO]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2024-09-30 10:46:40,434.434] _internal.py -> _log line:96 [INFO]: [33mPress CTRL+C to quit[0m
[2024-09-30 10:46:40,435.435] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:46:42,738.738] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:46:42,740.740] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:53:48,687.687] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\app_handler.py', reloading
[2024-09-30 10:53:48,943.943] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:53:51,404.404] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:53:51,406.406] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:53:55,887.887] http.py -> _register_error_handler line:66 [ERROR]: An error occurred: cannot pickle 'coroutine' object
Traceback (most recent call last):
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\Code\llmops\llmops-api\internal\handler\app_handler.py", line 119, in ping
    return success_json(self.embedding_service.embeddings.aembed_query("你好，你是"))
  File "D:\Code\llmops\llmops-api\pkg\response\response.py", line 31, in success_json
    return json(Response(code=HttpCode.SUCCESS, message="", data=data))
  File "D:\Code\llmops\llmops-api\pkg\response\response.py", line 26, in json
    return jsonify(data), 200
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\json\provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\json\provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
  File "D:\Env\python\python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "D:\Env\python\python310\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "D:\Env\python\python310\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\json\provider.py", line 116, in _default
    return dataclasses.asdict(o)
  File "D:\Env\python\python310\lib\dataclasses.py", line 1238, in asdict
    return _asdict_inner(obj, dict_factory)
  File "D:\Env\python\python310\lib\dataclasses.py", line 1245, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "D:\Env\python\python310\lib\dataclasses.py", line 1279, in _asdict_inner
    return copy.deepcopy(obj)
  File "D:\Env\python\python310\lib\copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'coroutine' object
[2024-09-30 10:53:55,909.909] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 10:53:55] "[35m[1mGET /ping HTTP/1.1[0m" 500 -
[2024-09-30 10:54:36,325.325] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\app_handler.py', reloading
[2024-09-30 10:54:36,626.626] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:54:39,057.057] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:54:39,060.060] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:54:44,005.005] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\app_handler.py', reloading
[2024-09-30 10:54:44,235.235] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:54:46,896.896] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:54:46,899.899] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:54:54,093.093] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\app_handler.py', reloading
[2024-09-30 10:54:54,337.337] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:54:56,717.717] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:54:56,720.720] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:54:58,791.791] http.py -> _register_error_handler line:66 [ERROR]: An error occurred: cannot pickle 'coroutine' object
Traceback (most recent call last):
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\Code\llmops\llmops-api\internal\handler\app_handler.py", line 122, in ping
    return success_json({"vectors": vectors})
  File "D:\Code\llmops\llmops-api\pkg\response\response.py", line 31, in success_json
    return json(Response(code=HttpCode.SUCCESS, message="", data=data))
  File "D:\Code\llmops\llmops-api\pkg\response\response.py", line 26, in json
    return jsonify(data), 200
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\json\provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\json\provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
  File "D:\Env\python\python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "D:\Env\python\python310\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "D:\Env\python\python310\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\json\provider.py", line 116, in _default
    return dataclasses.asdict(o)
  File "D:\Env\python\python310\lib\dataclasses.py", line 1238, in asdict
    return _asdict_inner(obj, dict_factory)
  File "D:\Env\python\python310\lib\dataclasses.py", line 1245, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "D:\Env\python\python310\lib\dataclasses.py", line 1275, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
  File "D:\Env\python\python310\lib\dataclasses.py", line 1276, in <genexpr>
    _asdict_inner(v, dict_factory))
  File "D:\Env\python\python310\lib\dataclasses.py", line 1279, in _asdict_inner
    return copy.deepcopy(obj)
  File "D:\Env\python\python310\lib\copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'coroutine' object
[2024-09-30 10:54:58,811.811] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 10:54:58] "[35m[1mGET /ping HTTP/1.1[0m" 500 -
[2024-09-30 10:55:17,165.165] http.py -> _register_error_handler line:66 [ERROR]: An error occurred: cannot pickle 'coroutine' object
Traceback (most recent call last):
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\Code\llmops\llmops-api\internal\handler\app_handler.py", line 122, in ping
    return success_json({"vectors": vectors})
  File "D:\Code\llmops\llmops-api\pkg\response\response.py", line 31, in success_json
    return json(Response(code=HttpCode.SUCCESS, message="", data=data))
  File "D:\Code\llmops\llmops-api\pkg\response\response.py", line 26, in json
    return jsonify(data), 200
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\json\__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\json\provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\json\provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
  File "D:\Env\python\python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "D:\Env\python\python310\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "D:\Env\python\python310\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\json\provider.py", line 116, in _default
    return dataclasses.asdict(o)
  File "D:\Env\python\python310\lib\dataclasses.py", line 1238, in asdict
    return _asdict_inner(obj, dict_factory)
  File "D:\Env\python\python310\lib\dataclasses.py", line 1245, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "D:\Env\python\python310\lib\dataclasses.py", line 1275, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
  File "D:\Env\python\python310\lib\dataclasses.py", line 1276, in <genexpr>
    _asdict_inner(v, dict_factory))
  File "D:\Env\python\python310\lib\dataclasses.py", line 1279, in _asdict_inner
    return copy.deepcopy(obj)
  File "D:\Env\python\python310\lib\copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'coroutine' object
[2024-09-30 10:55:17,183.183] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 10:55:17] "[35m[1mGET /ping HTTP/1.1[0m" 500 -
[2024-09-30 10:55:30,739.739] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\app_handler.py', reloading
[2024-09-30 10:55:31,003.003] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:55:33,623.623] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:55:33,625.625] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:55:33,981.981] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 10:55:33] "GET /ping HTTP/1.1" 200 -
[2024-09-30 10:55:52,211.211] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\app_handler.py', reloading
[2024-09-30 10:55:52,462.462] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:55:55,059.059] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:55:55,062.062] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:56:01,442.442] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 10:56:01] "GET /ping HTTP/1.1" 200 -
[2024-09-30 10:56:28,531.531] _internal.py -> _log line:96 [INFO]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2024-09-30 10:56:28,531.531] _internal.py -> _log line:96 [INFO]: [33mPress CTRL+C to quit[0m
[2024-09-30 10:56:28,532.532] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 10:56:30,866.866] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 10:56:30,869.869] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 10:56:32,354.354] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 10:56:32] "GET /ping HTTP/1.1" 200 -
[2024-09-30 11:04:34,172.172] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\app_handler.py', reloading
[2024-09-30 11:04:34,454.454] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:04:37,062.062] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:04:37,065.065] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:04:38,432.432] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\app_handler.py', reloading
[2024-09-30 11:04:38,686.686] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:04:41,346.346] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:04:41,349.349] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:04:42,742.742] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embedding_service.py', reloading
[2024-09-30 11:04:43,003.003] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:04:45,406.406] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:04:45,409.409] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:04:55,920.920] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embeddings_service.py', reloading
[2024-09-30 11:04:56,166.166] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:04:58,549.549] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:04:58,552.552] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:08:51,915.915] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\本地Embedding模型安装.py', reloading
[2024-09-30 11:08:52,240.240] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:08:54,842.842] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:08:54,845.845] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:09:00,799.799] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\本地Embedding模型安装.py', reloading
[2024-09-30 11:09:01,054.054] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:09:03,422.422] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:09:03,424.424] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:09:25,522.522] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\本地Embedding模型安装.py', reloading
[2024-09-30 11:09:25,787.787] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:09:28,115.115] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:09:28,118.118] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:09:29,473.473] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\本地Embedding模型安装.py', reloading
[2024-09-30 11:09:29,742.742] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:09:32,104.104] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:09:32,107.107] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:12:14,893.893] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\本地Embedding模型安装.py', reloading
[2024-09-30 11:12:15,140.140] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:12:17,579.579] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:12:17,582.582] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:12:29,411.411] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\本地Embedding模型安装.py', reloading
[2024-09-30 11:12:29,658.658] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:12:31,992.992] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:12:31,994.994] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:12:33,392.392] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\本地Embedding模型安装.py', reloading
[2024-09-30 11:12:33,646.646] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:12:35,965.965] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:12:35,966.966] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:13:20,935.935] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\core\\embeddings\\__init__.py', reloading
[2024-09-30 11:13:21,211.211] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:13:23,618.618] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:13:23,621.621] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:14:27,979.979] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embeddings_service.py', reloading
[2024-09-30 11:14:28,228.228] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:14:30,941.941] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:14:30,943.943] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:14:41,337.337] _internal.py -> _log line:96 [INFO]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2024-09-30 11:14:41,337.337] _internal.py -> _log line:96 [INFO]: [33mPress CTRL+C to quit[0m
[2024-09-30 11:14:41,338.338] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:14:43,619.619] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:14:43,621.621] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:14:46,825.825] http.py -> _register_error_handler line:66 [ERROR]: An error occurred: module 'internal.task.demo_task' has no attribute 'delay'
Traceback (most recent call last):
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\Code\llmops\llmops-api\internal\handler\app_handler.py", line 118, in ping
    demo_task.delay(uuid.uuid4())
AttributeError: module 'internal.task.demo_task' has no attribute 'delay'
[2024-09-30 11:14:46,834.834] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 11:14:46] "[35m[1mGET /ping HTTP/1.1[0m" 500 -
[2024-09-30 11:15:06,724.724] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\app_handler.py', reloading
[2024-09-30 11:15:06,967.967] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:15:09,277.277] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:15:09,280.280] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:15:10,322.322] base.py -> _exec_single_context line:1903 [INFO]: select pg_catalog.version()
[2024-09-30 11:15:10,322.322] base.py -> _exec_single_context line:1908 [INFO]: [raw sql] {}
[2024-09-30 11:15:10,322.322] base.py -> _exec_single_context line:1903 [INFO]: select current_schema()
[2024-09-30 11:15:10,322.322] base.py -> _exec_single_context line:1908 [INFO]: [raw sql] {}
[2024-09-30 11:15:10,323.323] base.py -> _exec_single_context line:1903 [INFO]: show standard_conforming_strings
[2024-09-30 11:15:10,323.323] base.py -> _exec_single_context line:1908 [INFO]: [raw sql] {}
[2024-09-30 11:15:10,324.324] base.py -> _begin_impl line:1103 [INFO]: BEGIN (implicit)
[2024-09-30 11:15:10,325.325] base.py -> _exec_single_context line:1903 [INFO]: SELECT api_tool.id AS api_tool_id, api_tool.account_id AS api_tool_account_id, api_tool.provider_id AS api_tool_provider_id, api_tool.name AS api_tool_name, api_tool.description AS api_tool_description, api_tool.url AS api_tool_url, api_tool.method AS api_tool_method, api_tool.parameters AS api_tool_parameters, api_tool.updated_at AS api_tool_updated_at, api_tool.created_at AS api_tool_created_at 
FROM api_tool 
WHERE api_tool.provider_id = %(provider_id_1)s::UUID AND api_tool.name = %(name_1)s
[2024-09-30 11:15:10,325.325] base.py -> _exec_single_context line:1908 [INFO]: [generated in 0.00013s] {'provider_id_1': 'd72bb9d7-8794-4caf-bd60-1f992c537065', 'name_1': 'YoudaoSuggest'}
[2024-09-30 11:15:10,328.328] base.py -> _exec_single_context line:1903 [INFO]: SELECT api_tool_provider.id AS api_tool_provider_id, api_tool_provider.account_id AS api_tool_provider_account_id, api_tool_provider.name AS api_tool_provider_name, api_tool_provider.icon AS api_tool_provider_icon, api_tool_provider.description AS api_tool_provider_description, api_tool_provider.openapi_schema AS api_tool_provider_openapi_schema, api_tool_provider.headers AS api_tool_provider_headers, api_tool_provider.updated_at AS api_tool_provider_updated_at, api_tool_provider.created_at AS api_tool_provider_created_at 
FROM api_tool_provider 
WHERE api_tool_provider.id = %(pk_1)s::UUID
[2024-09-30 11:15:10,328.328] base.py -> _exec_single_context line:1908 [INFO]: [generated in 0.00013s] {'pk_1': UUID('d72bb9d7-8794-4caf-bd60-1f992c537065')}
[2024-09-30 11:15:10,530.530] base.py -> _rollback_impl line:1129 [INFO]: ROLLBACK
[2024-09-30 11:15:10,531.531] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 11:15:10] "GET /ping HTTP/1.1" 200 -
[2024-09-30 11:15:47,399.399] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\app_handler.py', reloading
[2024-09-30 11:15:47,644.644] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:15:49,978.978] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:15:49,981.981] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:15:51,517.517] http.py -> _register_error_handler line:66 [ERROR]: An error occurred: name 'os' is not defined
Traceback (most recent call last):
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\Code\llmops\llmops-api\internal\handler\app_handler.py", line 119, in ping
    print("当前路径:", os.getcwd())
NameError: name 'os' is not defined
[2024-09-30 11:15:51,529.529] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 11:15:51] "[35m[1mGET /ping HTTP/1.1[0m" 500 -
[2024-09-30 11:15:58,337.337] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\app_handler.py', reloading
[2024-09-30 11:15:58,722.722] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:16:01,250.250] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:16:01,253.253] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:16:01,629.629] base.py -> _exec_single_context line:1903 [INFO]: select pg_catalog.version()
[2024-09-30 11:16:01,629.629] base.py -> _exec_single_context line:1908 [INFO]: [raw sql] {}
[2024-09-30 11:16:01,630.630] base.py -> _exec_single_context line:1903 [INFO]: select current_schema()
[2024-09-30 11:16:01,630.630] base.py -> _exec_single_context line:1908 [INFO]: [raw sql] {}
[2024-09-30 11:16:01,631.631] base.py -> _exec_single_context line:1903 [INFO]: show standard_conforming_strings
[2024-09-30 11:16:01,631.631] base.py -> _exec_single_context line:1908 [INFO]: [raw sql] {}
[2024-09-30 11:16:01,632.632] base.py -> _begin_impl line:1103 [INFO]: BEGIN (implicit)
[2024-09-30 11:16:01,633.633] base.py -> _exec_single_context line:1903 [INFO]: SELECT api_tool.id AS api_tool_id, api_tool.account_id AS api_tool_account_id, api_tool.provider_id AS api_tool_provider_id, api_tool.name AS api_tool_name, api_tool.description AS api_tool_description, api_tool.url AS api_tool_url, api_tool.method AS api_tool_method, api_tool.parameters AS api_tool_parameters, api_tool.updated_at AS api_tool_updated_at, api_tool.created_at AS api_tool_created_at 
FROM api_tool 
WHERE api_tool.provider_id = %(provider_id_1)s::UUID AND api_tool.name = %(name_1)s
[2024-09-30 11:16:01,633.633] base.py -> _exec_single_context line:1908 [INFO]: [generated in 0.00015s] {'provider_id_1': 'd72bb9d7-8794-4caf-bd60-1f992c537065', 'name_1': 'YoudaoSuggest'}
[2024-09-30 11:16:01,636.636] base.py -> _exec_single_context line:1903 [INFO]: SELECT api_tool_provider.id AS api_tool_provider_id, api_tool_provider.account_id AS api_tool_provider_account_id, api_tool_provider.name AS api_tool_provider_name, api_tool_provider.icon AS api_tool_provider_icon, api_tool_provider.description AS api_tool_provider_description, api_tool_provider.openapi_schema AS api_tool_provider_openapi_schema, api_tool_provider.headers AS api_tool_provider_headers, api_tool_provider.updated_at AS api_tool_provider_updated_at, api_tool_provider.created_at AS api_tool_provider_created_at 
FROM api_tool_provider 
WHERE api_tool_provider.id = %(pk_1)s::UUID
[2024-09-30 11:16:01,636.636] base.py -> _exec_single_context line:1908 [INFO]: [generated in 0.00014s] {'pk_1': UUID('d72bb9d7-8794-4caf-bd60-1f992c537065')}
[2024-09-30 11:16:01,729.729] base.py -> _rollback_impl line:1129 [INFO]: ROLLBACK
[2024-09-30 11:16:01,729.729] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 11:16:01] "GET /ping HTTP/1.1" 200 -
[2024-09-30 11:17:14,564.564] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embeddings_service.py', reloading
[2024-09-30 11:17:14,798.798] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:17:17,188.188] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:17:17,191.191] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:17:26,607.607] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\core\\embeddings\\__init__.py', reloading
[2024-09-30 11:17:26,841.841] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:17:29,213.213] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:17:29,215.215] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:17:31,660.660] base.py -> _exec_single_context line:1903 [INFO]: select pg_catalog.version()
[2024-09-30 11:17:31,661.661] base.py -> _exec_single_context line:1908 [INFO]: [raw sql] {}
[2024-09-30 11:17:31,662.662] base.py -> _exec_single_context line:1903 [INFO]: select current_schema()
[2024-09-30 11:17:31,662.662] base.py -> _exec_single_context line:1908 [INFO]: [raw sql] {}
[2024-09-30 11:17:31,662.662] base.py -> _exec_single_context line:1903 [INFO]: show standard_conforming_strings
[2024-09-30 11:17:31,662.662] base.py -> _exec_single_context line:1908 [INFO]: [raw sql] {}
[2024-09-30 11:17:31,663.663] base.py -> _begin_impl line:1103 [INFO]: BEGIN (implicit)
[2024-09-30 11:17:31,665.665] base.py -> _exec_single_context line:1903 [INFO]: SELECT api_tool.id AS api_tool_id, api_tool.account_id AS api_tool_account_id, api_tool.provider_id AS api_tool_provider_id, api_tool.name AS api_tool_name, api_tool.description AS api_tool_description, api_tool.url AS api_tool_url, api_tool.method AS api_tool_method, api_tool.parameters AS api_tool_parameters, api_tool.updated_at AS api_tool_updated_at, api_tool.created_at AS api_tool_created_at 
FROM api_tool 
WHERE api_tool.provider_id = %(provider_id_1)s::UUID AND api_tool.name = %(name_1)s
[2024-09-30 11:17:31,665.665] base.py -> _exec_single_context line:1908 [INFO]: [generated in 0.00031s] {'provider_id_1': 'd72bb9d7-8794-4caf-bd60-1f992c537065', 'name_1': 'YoudaoSuggest'}
[2024-09-30 11:17:31,668.668] base.py -> _exec_single_context line:1903 [INFO]: SELECT api_tool_provider.id AS api_tool_provider_id, api_tool_provider.account_id AS api_tool_provider_account_id, api_tool_provider.name AS api_tool_provider_name, api_tool_provider.icon AS api_tool_provider_icon, api_tool_provider.description AS api_tool_provider_description, api_tool_provider.openapi_schema AS api_tool_provider_openapi_schema, api_tool_provider.headers AS api_tool_provider_headers, api_tool_provider.updated_at AS api_tool_provider_updated_at, api_tool_provider.created_at AS api_tool_provider_created_at 
FROM api_tool_provider 
WHERE api_tool_provider.id = %(pk_1)s::UUID
[2024-09-30 11:17:31,669.669] base.py -> _exec_single_context line:1908 [INFO]: [generated in 0.00017s] {'pk_1': UUID('d72bb9d7-8794-4caf-bd60-1f992c537065')}
[2024-09-30 11:17:31,761.761] base.py -> _rollback_impl line:1129 [INFO]: ROLLBACK
[2024-09-30 11:17:31,761.761] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 11:17:31] "GET /ping HTTP/1.1" 200 -
[2024-09-30 11:18:24,560.560] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\app_handler.py', reloading
[2024-09-30 11:18:24,801.801] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:19:59,652.652] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:19:59,655.655] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:20:00,546.546] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 11:20:00] "GET /ping HTTP/1.1" 200 -
[2024-09-30 11:20:27,084.084] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 11:20:27] "GET /ping HTTP/1.1" 200 -
[2024-09-30 11:20:28,489.489] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 11:20:28] "GET /ping HTTP/1.1" 200 -
[2024-09-30 11:20:48,726.726] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\app_handler.py', reloading
[2024-09-30 11:20:49,355.355] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:20:57,091.091] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:20:57,094.094] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:20:58,048.048] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 11:20:58] "GET /ping HTTP/1.1" 200 -
[2024-09-30 11:21:02,479.479] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 11:21:02] "GET /ping HTTP/1.1" 200 -
[2024-09-30 11:25:42,689.689] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\app_handler.py', reloading
[2024-09-30 11:25:43,348.348] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:25:51,192.192] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:25:51,196.196] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:25:56,925.925] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 11:25:56] "GET /ping?query=你好，我叫慕小课，你是？ HTTP/1.1" 200 -
[2024-09-30 11:26:03,588.588] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 11:26:03] "GET /ping?query=好的，谢谢 HTTP/1.1" 200 -
[2024-09-30 11:26:33,321.321] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\app_handler.py', reloading
[2024-09-30 11:26:33,896.896] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:26:41,659.659] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:26:41,662.662] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:33:20,164.164] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\vector_database_service.py', reloading
[2024-09-30 11:33:20,742.742] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:33:31,470.470] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:33:31,472.472] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:33:56,593.593] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\vector_database_service.py', reloading
[2024-09-30 11:33:57,192.192] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:34:07,477.477] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:34:07,479.479] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:53:43,212.212] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\document_handler.py', reloading
[2024-09-30 11:53:43,759.759] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:53:54,450.450] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:53:54,453.453] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:53:58,863.863] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\document_handler.py', reloading
[2024-09-30 11:53:59,388.388] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:54:09,931.931] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:54:09,934.934] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:54:32,169.169] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\document_handler.py', reloading
[2024-09-30 11:54:32,732.732] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:54:42,614.614] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:54:42,616.616] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:57:13,583.583] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 11:57:14,138.138] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:57:24,084.084] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:57:24,087.087] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:57:32,351.351] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 11:57:32,899.899] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:57:43,017.017] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:57:43,020.020] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:57:52,645.645] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 11:57:53,266.266] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 11:58:03,584.584] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 11:58:03,587.587] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 11:59:51,717.717] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 11:59:52,343.343] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:00:03,627.627] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:00:03,630.630] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:00:18,226.226] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 12:00:18,867.867] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:00:29,871.871] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:00:29,874.874] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:00:38,024.024] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\schema.py', reloading
[2024-09-30 12:00:38,602.602] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:00:48,623.623] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:00:48,626.626] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:00:51,598.598] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\schema.py', reloading
[2024-09-30 12:00:52,194.194] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:01:02,675.675] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:01:02,676.676] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:01:06,628.628] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\schema.py', reloading
[2024-09-30 12:01:07,190.190] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:01:08,655.655] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:01:18,545.545] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:01:18,547.547] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:01:21,309.309] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 12:01:21,851.851] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:01:31,449.449] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:01:31,450.450] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:01:34,106.106] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 12:01:34,649.649] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:01:44,026.026] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:01:44,027.027] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:02:07,130.130] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 12:02:07,689.689] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:02:18,307.307] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:02:18,310.310] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:02:21,288.288] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 12:02:21,875.875] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:02:31,857.857] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:02:31,859.859] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:03:36,624.624] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 12:03:37,182.182] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:03:47,296.296] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:03:47,299.299] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:03:49,039.039] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 12:03:49,616.616] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:03:59,710.710] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:03:59,712.712] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:04:16,808.808] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 12:04:17,347.347] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:04:28,202.202] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:04:28,204.204] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:04:28,649.649] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 12:04:29,225.225] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:04:39,633.633] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:04:39,635.635] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:05:09,450.450] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\document_handler.py', reloading
[2024-09-30 12:05:10,001.001] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:05:20,532.532] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:05:20,535.535] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:05:22,263.263] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\document_handler.py', reloading
[2024-09-30 12:05:22,815.815] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:05:33,736.736] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:05:33,739.739] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:06:14,111.111] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 12:06:14,653.653] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:06:25,289.289] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:06:25,292.292] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:06:42,398.398] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 12:06:42,939.939] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:06:53,380.380] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:06:53,383.383] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:07:01,517.517] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 12:07:02,073.073] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:07:12,135.135] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:07:12,137.137] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:07:31,785.785] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 12:07:32,348.348] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:07:42,400.400] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:07:42,402.402] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:07:56,989.989] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\entity\\dataset_entity.py', reloading
[2024-09-30 12:07:57,524.524] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:08:08,993.993] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:08:08,996.996] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:09:23,642.642] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 12:09:24,220.220] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:09:34,694.694] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:09:34,697.697] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:09:59,678.678] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 12:10:00,279.279] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:10:10,946.946] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:10:10,949.949] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:10:14,065.065] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 12:10:14,614.614] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:10:26,127.127] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:10:26,129.129] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:17:19,644.644] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 12:17:20,265.265] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:17:30,655.655] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:17:30,658.658] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:18:36,287.287] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 12:18:36,845.845] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:18:47,317.317] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:18:47,319.319] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:20:05,729.729] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 12:20:06,295.295] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:20:16,624.624] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:20:16,627.627] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:20:55,446.446] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 12:20:55,984.984] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:21:07,823.823] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:21:07,826.826] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:21:12,275.275] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 12:21:12,821.821] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:21:23,181.181] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:21:23,184.184] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:21:28,756.756] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 12:21:29,311.311] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:21:39,280.280] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:21:39,283.283] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:21:44,833.833] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 12:21:45,480.480] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:21:57,020.020] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:21:57,023.023] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:22:01,356.356] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 12:22:01,955.955] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:22:13,317.317] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:22:13,320.320] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:22:16,433.433] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 12:22:16,972.972] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:22:26,902.902] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:22:26,905.905] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:22:39,035.035] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 12:22:39,624.624] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:22:50,025.025] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:22:50,027.027] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 12:23:00,828.828] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 12:23:01,364.364] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 12:23:11,865.865] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 12:23:11,867.867] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 13:22:55,409.409] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\vector_database_service.py', reloading
[2024-09-30 13:22:56,042.042] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 13:26:58,892.892] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 13:28:10,991.991] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 13:28:13,267.267] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 13:28:13,268.268] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 13:35:58,485.485] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embeddings_service.py', reloading
[2024-09-30 13:35:58,756.756] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 13:36:01,238.238] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 13:36:01,240.240] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 13:40:56,589.589] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embeddings_service.py', reloading
[2024-09-30 13:40:56,820.820] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 13:40:59,282.282] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 13:40:59,284.284] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 13:43:31,754.754] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embeddings_service.py', reloading
[2024-09-30 13:43:32,001.001] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 13:43:34,342.342] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 13:43:34,345.345] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 13:44:23,751.751] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embeddings_service.py', reloading
[2024-09-30 13:44:23,983.983] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 13:44:26,511.511] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 13:44:26,514.514] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 13:45:18,187.187] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embeddings_service.py', reloading
[2024-09-30 13:45:18,433.433] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 13:45:20,840.840] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 13:45:20,843.843] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 13:50:30,733.733] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embeddings_service.py', reloading
[2024-09-30 13:50:30,984.984] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 13:50:33,258.258] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 13:50:33,260.260] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 13:55:14,149.149] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\本地embedding模型.py', reloading
[2024-09-30 13:55:14,417.417] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 13:55:17,006.006] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 13:55:17,008.008] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 13:55:25,350.350] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\本地embedding模型.py', reloading
[2024-09-30 13:55:25,626.626] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 13:55:28,031.031] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 13:55:28,033.033] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 13:55:38,689.689] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\本地embedding模型.py', reloading
[2024-09-30 13:55:38,933.933] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 13:55:41,467.467] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 13:55:41,470.470] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 13:56:05,862.862] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\本地embedding模型.py', reloading
[2024-09-30 13:56:06,120.120] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 13:56:08,688.688] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 13:56:08,690.690] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 14:00:24,374.374] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embeddings_service.py', reloading
[2024-09-30 14:00:24,664.664] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 14:00:27,226.226] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 14:00:27,228.228] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 14:01:47,001.001] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\core\\embeddings\\__init__.py', reloading
[2024-09-30 14:01:47,231.231] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 14:01:49,549.549] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 14:01:49,552.552] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 14:02:17,277.277] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\core\\embeddings\\__init__.py', reloading
[2024-09-30 14:02:17,529.529] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 14:02:20,032.032] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 14:02:20,037.037] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 14:02:59,603.603] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\luj.py', reloading
[2024-09-30 14:02:59,888.888] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 14:03:02,410.410] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 14:03:02,413.413] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 14:03:24,420.420] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embeddings_service.py', reloading
[2024-09-30 14:03:24,665.665] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 14:03:26,987.987] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 14:03:26,990.990] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 14:03:45,522.522] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embeddings_service.py', reloading
[2024-09-30 14:03:45,785.785] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 14:03:48,319.319] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 14:03:48,322.322] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 14:04:17,782.782] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\embeddings_service.py', reloading
[2024-09-30 14:04:18,015.015] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 14:04:20,369.369] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 14:04:20,371.371] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 14:04:37,818.818] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\__init__.py', reloading
[2024-09-30 14:04:38,075.075] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 14:04:40,505.505] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 14:04:40,507.507] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 14:06:06,752.752] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\dataset_handler.py', reloading
[2024-09-30 14:06:07,024.024] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 14:06:22,476.476] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 14:06:22,479.479] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 14:06:29,692.692] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\router\\router.py', reloading
[2024-09-30 14:06:30,282.282] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 14:06:40,966.966] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 14:06:40,969.969] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 14:06:52,078.078] _internal.py -> _log line:96 [INFO]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2024-09-30 14:06:52,079.079] _internal.py -> _log line:96 [INFO]: [33mPress CTRL+C to quit[0m
[2024-09-30 14:06:52,080.080] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 14:07:02,730.730] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 14:07:02,733.733] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 14:08:10,943.943] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 14:08:10] "GET /datasets/embeddings?query=你好，你是？ HTTP/1.1" 200 -
[2024-09-30 14:08:41,193.193] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 14:08:41] "GET /datasets/embeddings?query=我叫慕小课，我喜欢打篮球，你喜欢什么呢？ HTTP/1.1" 200 -
[2024-09-30 14:09:31,464.464] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 14:09:31] "GET /datasets/embeddings?query=我叫慕小课，我喜欢打篮球，你喜欢什么呢？ HTTP/1.1" 200 -
[2024-09-30 14:11:26,359.359] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\vector_database_service.py', reloading
[2024-09-30 14:11:26,947.947] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 15:02:18,962.962] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 15:02:39,056.056] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 15:04:38,769.769] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 15:14:50,633.633] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 15:15:02,762.762] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 15:15:02,770.770] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 15:19:32,075.075] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\vector_database_service.py', reloading
[2024-09-30 15:19:32,623.623] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 15:19:48,356.356] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 15:19:48,359.359] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 15:28:51,919.919] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\jieba_service.py', reloading
[2024-09-30 15:28:52,523.523] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 15:29:09,905.905] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 15:29:09,908.908] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 15:29:46,599.599] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\jieba_service.py', reloading
[2024-09-30 15:29:47,185.185] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 15:30:02,597.597] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 15:30:02,599.599] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 15:30:55,159.159] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\jieba_service.py', reloading
[2024-09-30 15:30:55,814.814] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 15:31:12,339.339] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 15:31:12,342.342] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 15:31:50,863.863] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\dataset_handler.py', reloading
[2024-09-30 15:31:51,455.455] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 15:32:09,439.439] _internal.py -> _log line:96 [INFO]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2024-09-30 15:32:09,439.439] _internal.py -> _log line:96 [INFO]: [33mPress CTRL+C to quit[0m
[2024-09-30 15:32:09,440.440] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 15:32:26,045.045] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 15:32:26,048.048] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 15:32:26,365.365] __init__.py -> initialize line:113 [DEBUG]: Building prefix dict from the default dictionary ...
[2024-09-30 15:32:26,729.729] __init__.py -> initialize line:146 [DEBUG]: Dumping model to file cache C:\Users\Administrator\AppData\Local\Temp\jieba.cache
[2024-09-30 15:32:26,758.758] __init__.py -> initialize line:164 [DEBUG]: Loading model cost 0.393 seconds.
[2024-09-30 15:32:26,758.758] __init__.py -> initialize line:166 [DEBUG]: Prefix dict has been built successfully.
[2024-09-30 15:32:26,759.759] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 15:32:26] "GET /datasets/embeddings?query=我叫慕小课，我喜欢打篮球，你喜欢什么呢？ HTTP/1.1" 200 -
[2024-09-30 15:33:15,185.185] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 15:33:15] "GET /datasets/embeddings?query=在宁静的森林深处，微风轻轻吹拂着树梢，阳光透过树叶洒下一道道光束。鸟儿在枝头欢快地歌唱，小溪潺潺流过，仿佛在低声诉说着大自然的秘密。一只小鹿警觉地从树丛中探出头，闻了闻空气中的气味，缓缓地向前迈步。四周的花朵在风中摇曳，散发出淡淡的芳香。天空中，几只白云悠悠飘过，给这一片宁静的土地增添了几分诗意。 HTTP/1.1" 200 -
[2024-09-30 15:47:03,160.160] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\document_handler.py', reloading
[2024-09-30 15:47:03,816.816] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 15:47:19,777.777] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 15:47:19,780.780] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 15:51:46,365.365] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\document_handler.py', reloading
[2024-09-30 15:51:46,978.978] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 15:52:03,477.477] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 15:52:03,483.483] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 15:54:21,882.882] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 15:54:22,493.493] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 15:54:38,515.515] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 15:54:38,518.518] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 15:55:06,028.028] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 15:55:06,617.617] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 15:55:22,213.213] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 15:55:22,215.215] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 15:55:25,326.326] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 15:55:25,929.929] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 15:55:42,401.401] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 15:55:42,404.404] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 15:55:57,173.173] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 15:55:57,789.789] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 15:56:14,946.946] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 15:56:14,949.949] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 15:56:29,558.558] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 15:56:30,166.166] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 15:56:46,205.205] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 15:56:46,208.208] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 15:57:34,070.070] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 15:57:34,735.735] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 15:57:51,106.106] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 15:57:51,109.109] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 15:58:00,591.591] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 15:58:01,253.253] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 15:58:18,891.891] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 15:58:18,893.893] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 15:58:29,698.698] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 15:58:30,261.261] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 15:58:45,398.398] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 15:58:45,401.401] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 15:59:55,373.373] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 15:59:56,011.011] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 16:00:13,289.289] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 16:00:13,292.292] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 16:00:30,595.595] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 16:00:31,171.171] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 16:00:46,406.406] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 16:00:46,408.408] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 16:00:59,782.782] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 16:01:00,393.393] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 16:01:17,176.176] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 16:01:17,179.179] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 16:01:24,207.207] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 16:01:24,792.792] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 16:01:40,136.136] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 16:01:40,139.139] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 16:01:53,536.536] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 16:01:54,206.206] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 16:02:10,167.167] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 16:02:10,169.169] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 16:02:28,748.748] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 16:02:29,361.361] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 16:02:46,282.282] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 16:02:46,285.285] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 16:02:50,794.794] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 16:02:51,394.394] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 16:03:07,089.089] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 16:03:07,090.090] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 16:03:12,123.123] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 16:03:12,778.778] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 16:03:28,011.011] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 16:03:28,013.013] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 16:03:56,740.740] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 16:03:57,379.379] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 16:04:13,941.941] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 16:04:13,942.942] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 16:04:27,434.434] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 16:04:28,008.008] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 16:04:43,429.429] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 16:04:43,429.429] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 16:05:04,230.230] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\document_handler.py', reloading
[2024-09-30 16:05:04,837.837] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 16:16:16,794.794] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 16:16:32,678.678] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 16:16:32,681.681] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 16:17:32,696.696] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\core\\file_extractor\\file_extractor.py', reloading
[2024-09-30 16:17:33,334.334] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 16:17:49,817.817] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 16:17:49,820.820] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 16:18:48,776.776] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\core\\file_extractor\\file_extractor.py', reloading
[2024-09-30 16:18:49,394.394] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 16:19:05,949.949] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 16:19:05,952.952] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 16:25:43,199.199] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\core\\file_extractor\\file_extractor.py', reloading
[2024-09-30 16:25:43,917.917] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 16:26:01,573.573] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 16:26:01,575.575] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 16:26:48,833.833] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\core\\file_extractor\\file_extractor.py', reloading
[2024-09-30 16:26:49,442.442] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 16:27:05,603.603] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 16:27:05,605.605] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 16:28:13,649.649] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\core\\file_extractor\\file_extractor.py', reloading
[2024-09-30 16:28:14,259.259] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 16:28:31,088.088] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 16:28:31,090.090] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 16:35:34,841.841] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\core\\file_extractor\\file_extractor.py', reloading
[2024-09-30 16:35:35,451.451] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 16:35:51,308.308] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 16:35:51,311.311] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 16:39:17,862.862] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\core\\file_extractor\\file_extractor.py', reloading
[2024-09-30 16:39:18,560.560] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 16:39:35,933.933] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 16:39:35,936.936] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 16:39:48,194.194] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\core\\file_extractor\\__init__.py', reloading
[2024-09-30 16:39:48,845.845] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 16:42:03,232.232] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 16:42:19,625.625] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 16:42:19,627.627] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 16:43:04,620.620] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\dataset_handler.py', reloading
[2024-09-30 16:43:05,275.275] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 16:43:21,118.118] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 16:43:21,120.120] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 16:43:38,614.614] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\dataset_handler.py', reloading
[2024-09-30 16:43:39,311.311] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 16:43:58,463.463] _internal.py -> _log line:96 [INFO]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2024-09-30 16:43:58,463.463] _internal.py -> _log line:96 [INFO]: [33mPress CTRL+C to quit[0m
[2024-09-30 16:43:58,464.464] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 16:44:14,782.782] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 16:44:14,785.785] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 16:44:15,116.116] base.py -> _exec_single_context line:1903 [INFO]: select pg_catalog.version()
[2024-09-30 16:44:15,116.116] base.py -> _exec_single_context line:1908 [INFO]: [raw sql] {}
[2024-09-30 16:44:15,116.116] base.py -> _exec_single_context line:1903 [INFO]: select current_schema()
[2024-09-30 16:44:15,117.117] base.py -> _exec_single_context line:1908 [INFO]: [raw sql] {}
[2024-09-30 16:44:15,117.117] base.py -> _exec_single_context line:1903 [INFO]: show standard_conforming_strings
[2024-09-30 16:44:15,117.117] base.py -> _exec_single_context line:1908 [INFO]: [raw sql] {}
[2024-09-30 16:44:15,118.118] base.py -> _begin_impl line:1103 [INFO]: BEGIN (implicit)
[2024-09-30 16:44:15,119.119] base.py -> _exec_single_context line:1903 [INFO]: SELECT upload_file.id AS upload_file_id, upload_file.account_id AS upload_file_account_id, upload_file.name AS upload_file_name, upload_file.key AS upload_file_key, upload_file.size AS upload_file_size, upload_file.extension AS upload_file_extension, upload_file.mime_type AS upload_file_mime_type, upload_file.hash AS upload_file_hash, upload_file.updated_at AS upload_file_updated_at, upload_file.created_at AS upload_file_created_at 
FROM upload_file 
WHERE upload_file.id = %(pk_1)s::UUID
[2024-09-30 16:44:15,119.119] base.py -> _exec_single_context line:1908 [INFO]: [generated in 0.00019s] {'pk_1': '0092971c-1f1f-4a1e-a7bd-4aac5f2c6991'}
[2024-09-30 16:44:17,912.912] base.py -> _rollback_impl line:1129 [INFO]: ROLLBACK
[2024-09-30 16:44:17,912.912] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 16:44:17] "GET /datasets/embeddings HTTP/1.1" 200 -
[2024-09-30 17:47:23,358.358] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\config\\config.py', reloading
[2024-09-30 17:47:24,298.298] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 17:47:41,509.509] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 17:47:41,510.510] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 17:47:52,359.359] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\config\\config.py', reloading
[2024-09-30 17:47:52,947.947] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 17:48:10,463.463] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 17:48:10,466.466] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 17:50:44,635.635] _internal.py -> _log line:96 [INFO]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2024-09-30 17:50:44,635.635] _internal.py -> _log line:96 [INFO]: [33mPress CTRL+C to quit[0m
[2024-09-30 17:50:44,636.636] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 17:51:04,450.450] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 17:51:04,456.456] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 17:57:54,968.968] _internal.py -> _log line:96 [INFO]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2024-09-30 17:57:54,968.968] _internal.py -> _log line:96 [INFO]: [33mPress CTRL+C to quit[0m
[2024-09-30 17:57:54,969.969] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 17:58:10,311.311] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 17:58:10,313.313] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 18:19:44,363.363] base.py -> _exec_single_context line:1903 [INFO]: select pg_catalog.version()
[2024-09-30 18:19:44,363.363] base.py -> _exec_single_context line:1908 [INFO]: [raw sql] {}
[2024-09-30 18:19:44,364.364] base.py -> _exec_single_context line:1903 [INFO]: select current_schema()
[2024-09-30 18:19:44,364.364] base.py -> _exec_single_context line:1908 [INFO]: [raw sql] {}
[2024-09-30 18:19:44,365.365] base.py -> _exec_single_context line:1903 [INFO]: show standard_conforming_strings
[2024-09-30 18:19:44,365.365] base.py -> _exec_single_context line:1908 [INFO]: [raw sql] {}
[2024-09-30 18:19:44,366.366] base.py -> _begin_impl line:1103 [INFO]: BEGIN (implicit)
[2024-09-30 18:19:44,368.368] base.py -> _exec_single_context line:1903 [INFO]: SELECT upload_file.id AS upload_file_id, upload_file.account_id AS upload_file_account_id, upload_file.name AS upload_file_name, upload_file.key AS upload_file_key, upload_file.size AS upload_file_size, upload_file.extension AS upload_file_extension, upload_file.mime_type AS upload_file_mime_type, upload_file.hash AS upload_file_hash, upload_file.updated_at AS upload_file_updated_at, upload_file.created_at AS upload_file_created_at 
FROM upload_file 
WHERE upload_file.id = %(pk_1)s::UUID
[2024-09-30 18:19:44,368.368] base.py -> _exec_single_context line:1908 [INFO]: [generated in 0.00024s] {'pk_1': '0092971c-1f1f-4a1e-a7bd-4aac5f2c6991'}
[2024-09-30 18:19:47,866.866] base.py -> _rollback_impl line:1129 [INFO]: ROLLBACK
[2024-09-30 18:19:47,867.867] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 18:19:47] "GET /datasets/embeddings HTTP/1.1" 200 -
[2024-09-30 19:36:15,908.908] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 19:36:16,767.767] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:36:34,446.446] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:36:34,449.449] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:36:41,473.473] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 19:36:42,063.063] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:36:59,202.202] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:36:59,204.204] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:37:12,645.645] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\service\\document_service.py', reloading
[2024-09-30 19:37:13,260.260] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:37:30,517.517] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:37:30,519.519] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:39:46,003.003] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\document_handler.py', reloading
[2024-09-30 19:39:46,592.592] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:40:02,896.896] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:40:02,899.899] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:40:13,868.868] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\document_handler.py', reloading
[2024-09-30 19:40:14,480.480] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:40:32,568.568] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:40:32,571.571] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:40:52,632.632] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\document_handler.py', reloading
[2024-09-30 19:40:53,231.231] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:41:09,372.372] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:41:09,374.374] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:41:53,889.889] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 19:41:54,537.537] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:42:11,184.184] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:42:11,186.186] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:42:12,680.680] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 19:42:13,333.333] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:42:29,358.358] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:42:29,359.359] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:42:42,906.906] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 19:42:43,486.486] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:43:01,910.910] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:43:01,913.913] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:43:06,315.315] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 19:43:06,926.926] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:43:24,088.088] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:43:24,090.090] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:44:08,200.200] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 19:44:08,875.875] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:44:31,876.876] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:44:31,879.879] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:45:14,023.023] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 19:45:14,647.647] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:45:31,645.645] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:45:31,648.648] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:45:51,893.893] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 19:45:52,521.521] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:46:10,140.140] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:46:10,143.143] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:46:13,242.242] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 19:46:13,891.891] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:46:33,292.292] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:46:33,295.295] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:46:36,470.470] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 19:46:37,135.135] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:46:53,002.002] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:46:53,005.005] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:47:01,364.364] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 19:47:01,988.988] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:47:19,468.468] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:47:19,471.471] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:48:56,151.151] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 19:48:56,768.768] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:49:17,117.117] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:49:17,119.119] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:49:20,319.319] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 19:49:20,970.970] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:49:37,328.328] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:49:37,330.330] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:49:53,469.469] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 19:49:54,080.080] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:50:13,502.502] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:50:13,506.506] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:52:33,995.995] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 19:52:34,639.639] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:52:52,638.638] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:52:52,641.641] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:53:30,783.783] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\document_handler.py', reloading
[2024-09-30 19:53:31,414.414] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:53:48,183.183] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:53:48,186.186] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:54:01,742.742] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\__init__.py', reloading
[2024-09-30 19:54:02,421.421] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:55:29,100.100] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:55:48,478.478] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:55:48,480.480] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:55:48,785.785] http.py -> _register_error_handler line:66 [ERROR]: An error occurred: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2024-09-30 19:55:48,806.806] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 19:55:48] "[35m[1mPOST /datasets/documents HTTP/1.1[0m" 500 -
[2024-09-30 19:56:04,389.389] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 19:56:04] "POST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1" 200 -
[2024-09-30 19:56:21,245.245] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 19:56:21] "POST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1" 200 -
[2024-09-30 19:56:37,001.001] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 19:56:37] "POST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1" 200 -
[2024-09-30 19:56:51,531.531] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 19:56:52,193.193] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:57:10,548.548] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:57:10,551.551] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:57:18,137.137] _internal.py -> _log line:96 [INFO]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2024-09-30 19:57:18,137.137] _internal.py -> _log line:96 [INFO]: [33mPress CTRL+C to quit[0m
[2024-09-30 19:57:18,138.138] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:57:21,013.013] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:57:21,016.016] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:57:28,063.063] http.py -> _register_error_handler line:66 [ERROR]: An error occurred: CreateDocumentsReq.validate_upload_file_ids() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\Code\llmops\llmops-api\internal\handler\document_handler.py", line 26, in create_documents
    if not req.validate():
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\wtforms\form.py", line 329, in validate
    return super().validate(extra)
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\wtforms\form.py", line 146, in validate
    if not field.validate(self, extra):
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\wtforms\fields\core.py", line 246, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\wtforms\fields\core.py", line 266, in _run_validation_chain
    validator(form, self)
TypeError: CreateDocumentsReq.validate_upload_file_ids() takes 2 positional arguments but 3 were given
[2024-09-30 19:57:28,075.075] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 19:57:28] "[35m[1mPOST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1[0m" 500 -
[2024-09-30 19:58:14,650.650] http.py -> _register_error_handler line:66 [ERROR]: An error occurred: CreateDocumentsReq.validate_upload_file_ids() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\Code\llmops\llmops-api\internal\handler\document_handler.py", line 26, in create_documents
    if not req.validate():
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\wtforms\form.py", line 329, in validate
    return super().validate(extra)
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\wtforms\form.py", line 146, in validate
    if not field.validate(self, extra):
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\wtforms\fields\core.py", line 246, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\wtforms\fields\core.py", line 266, in _run_validation_chain
    validator(form, self)
TypeError: CreateDocumentsReq.validate_upload_file_ids() takes 2 positional arguments but 3 were given
[2024-09-30 19:58:14,661.661] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 19:58:14] "[35m[1mPOST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1[0m" 500 -
[2024-09-30 19:58:52,317.317] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 19:58:52,640.640] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:58:55,772.772] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:58:55,775.775] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:58:59,459.459] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 19:58:59,749.749] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:59:03,019.019] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:59:03,022.022] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:59:03,374.374] http.py -> _register_error_handler line:66 [ERROR]: An error occurred: CreateDocumentsReq.validate_upload_file_ids() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\Code\llmops\llmops-api\internal\handler\document_handler.py", line 26, in create_documents
    if not req.validate():
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\wtforms\form.py", line 329, in validate
    return super().validate(extra)
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\wtforms\form.py", line 146, in validate
    if not field.validate(self, extra):
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\wtforms\fields\core.py", line 246, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "D:\Code\llmops\llmops-api\venv\lib\site-packages\wtforms\fields\core.py", line 266, in _run_validation_chain
    validator(form, self)
TypeError: CreateDocumentsReq.validate_upload_file_ids() takes 1 positional argument but 2 were given
[2024-09-30 19:59:03,386.386] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 19:59:03] "[35m[1mPOST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1[0m" 500 -
[2024-09-30 19:59:07,937.937] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 19:59:08,227.227] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:59:11,399.399] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:59:11,402.402] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:59:11,664.664] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 19:59:11] "POST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1" 200 -
[2024-09-30 19:59:45,260.260] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 19:59:45,569.569] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 19:59:48,744.744] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 19:59:48,747.747] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 19:59:58,221.221] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 19:59:58,530.530] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:00:01,577.577] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:00:01,580.580] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:00:32,991.991] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:00:33,265.265] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:00:36,377.377] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:00:36,379.379] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:01:12,409.409] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\entity\\dataset_entity.py', reloading
[2024-09-30 20:01:12,690.690] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:01:15,781.781] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:01:15,784.784] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:01:22,948.948] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\entity\\dataset_entity.py', reloading
[2024-09-30 20:01:23,254.254] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:01:25,684.684] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:01:33,475.475] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:01:36,549.549] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:01:36,551.551] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:01:43,714.714] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\entity\\dataset_entity.py', reloading
[2024-09-30 20:01:43,990.990] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:01:47,082.082] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:01:47,084.084] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:01:55,448.448] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\entity\\dataset_entity.py', reloading
[2024-09-30 20:01:55,727.727] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:01:59,054.054] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:01:59,057.057] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:02:00,498.498] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\entity\\dataset_entity.py', reloading
[2024-09-30 20:02:00,769.769] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:02:03,615.615] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:02:03,616.616] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:02:04,900.900] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\entity\\dataset_entity.py', reloading
[2024-09-30 20:02:05,196.196] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:02:08,325.325] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:02:08,327.327] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:02:09,585.585] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\entity\\dataset_entity.py', reloading
[2024-09-30 20:02:09,912.912] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:02:12,710.710] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:02:12,712.712] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:02:13,961.961] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\entity\\dataset_entity.py', reloading
[2024-09-30 20:02:14,228.228] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:02:17,214.214] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:02:17,216.216] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:02:19,599.599] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\entity\\dataset_entity.py', reloading
[2024-09-30 20:02:19,865.865] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:02:22,696.696] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:02:22,698.698] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:02:27,257.257] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\entity\\dataset_entity.py', reloading
[2024-09-30 20:02:27,523.523] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:02:30,447.447] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:02:30,448.448] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:02:33,906.906] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\entity\\dataset_entity.py', reloading
[2024-09-30 20:02:34,193.193] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:02:37,182.182] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:02:37,184.184] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:02:38,435.435] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\entity\\dataset_entity.py', reloading
[2024-09-30 20:02:38,717.717] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:02:41,665.665] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:02:41,666.666] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:02:42,954.954] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\entity\\dataset_entity.py', reloading
[2024-09-30 20:02:43,244.244] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:02:46,037.037] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:02:46,039.039] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:02:48,447.447] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\entity\\dataset_entity.py', reloading
[2024-09-30 20:02:48,745.745] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:02:51,508.508] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:02:51,510.510] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:02:52,794.794] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\entity\\dataset_entity.py', reloading
[2024-09-30 20:02:53,084.084] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:02:56,073.073] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:02:56,075.075] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:03:01,756.756] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\entity\\dataset_entity.py', reloading
[2024-09-30 20:03:02,032.032] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:03:06,349.349] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:03:09,556.556] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:03:12,280.280] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:03:12,282.282] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:08:52,528.528] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\entity\\dataset_entity.py', reloading
[2024-09-30 20:08:52,811.811] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:08:56,182.182] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:08:56,185.185] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:09:27,564.564] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:09:27,895.895] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:09:42,181.181] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:09:49,590.590] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:09:56,300.300] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:10:13,879.879] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:10:26,059.059] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:10:46,291.291] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:11:08,616.616] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:12:09,683.683] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:12:12,870.870] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:12:12,873.873] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:12:25,864.864] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:12:26,131.131] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:12:30,009.009] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:12:39,667.667] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:12:49,326.326] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:12:58,911.911] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:13:13,151.151] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:13:16,188.188] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:13:16,190.190] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:13:29,132.132] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:13:29,408.408] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:13:32,698.698] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:13:32,701.701] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:13:34,106.106] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 20:13:34] "POST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1" 200 -
[2024-09-30 20:13:43,651.651] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 20:13:43] "POST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1" 200 -
[2024-09-30 20:13:55,124.124] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 20:13:55] "POST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1" 200 -
[2024-09-30 20:14:37,262.262] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:14:37,594.594] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:14:40,653.653] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:14:40,655.655] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:14:40,816.816] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 20:14:40] "[35m[1mPOST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1[0m" 500 -
[2024-09-30 20:14:46,207.207] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 20:14:46] "[35m[1mPOST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1[0m" 500 -
[2024-09-30 20:14:50,392.392] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 20:14:50] "[35m[1mPOST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1[0m" 500 -
[2024-09-30 20:15:05,968.968] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:15:06,260.260] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:15:09,330.330] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:15:09,333.333] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:15:12,164.164] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 20:15:12] "[35m[1mPOST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1[0m" 500 -
[2024-09-30 20:15:38,480.480] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\handler\\document_handler.py', reloading
[2024-09-30 20:15:38,752.752] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:15:42,498.498] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:15:42,501.501] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:15:43,572.572] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 20:15:43] "POST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1" 200 -
[2024-09-30 20:15:48,665.665] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 20:15:48] "POST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1" 200 -
[2024-09-30 20:15:51,249.249] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 20:15:51] "POST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1" 200 -
[2024-09-30 20:16:19,659.659] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:16:19,943.943] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:16:23,118.118] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:16:23,121.121] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:16:23,275.275] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 20:16:23] "POST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1" 200 -
[2024-09-30 20:16:34,971.971] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:16:35,252.252] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:16:38,471.471] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:16:38,474.474] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:16:39,101.101] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 20:16:39] "POST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1" 200 -
[2024-09-30 20:16:43,392.392] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:16:43,685.685] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:16:46,880.880] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:16:46,883.883] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:16:57,575.575] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:16:57,842.842] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:17:01,016.016] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:17:01,019.019] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:17:04,766.766] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 20:17:04] "POST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1" 200 -
[2024-09-30 20:17:17,435.435] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:17:17,725.725] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:17:20,830.830] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:17:20,833.833] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:17:23,957.957] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 20:17:23] "POST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1" 200 -
[2024-09-30 20:17:45,306.306] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:17:45,571.571] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:17:48,805.805] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:17:48,808.808] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:17:49,144.144] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 20:17:49] "POST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1" 200 -
[2024-09-30 20:17:55,979.979] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:17:56,246.246] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:17:59,301.301] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:17:59,304.304] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:18:08,803.803] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:18:09,071.071] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:18:12,296.296] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:18:12,299.299] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:18:20,630.630] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:18:20,943.943] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:18:24,130.130] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:18:24,133.133] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:18:24,283.283] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 20:18:24] "POST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1" 200 -
[2024-09-30 20:18:30,559.559] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 20:18:30] "POST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1" 200 -
[2024-09-30 20:19:22,557.557] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:19:22,856.856] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:19:25,926.926] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:19:25,928.928] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:19:26,076.076] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 20:19:26] "POST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1" 200 -
[2024-09-30 20:19:53,883.883] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:19:54,183.183] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:19:57,357.357] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:19:57,361.361] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:19:57,523.523] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 20:19:57] "POST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1" 200 -
[2024-09-30 20:20:36,886.886] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:20:37,161.161] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:20:40,255.255] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:20:40,258.258] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:20:40,662.662] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 20:20:40] "POST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1" 200 -
[2024-09-30 20:20:50,939.939] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:20:51,240.240] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:20:54,507.507] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:20:54,510.510] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:20:57,052.052] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:20:57,358.358] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:21:00,621.621] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:21:00,624.624] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:21:00,777.777] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 20:21:00] "POST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1" 200 -
[2024-09-30 20:21:19,504.504] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:21:19,773.773] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:21:22,881.881] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:21:22,884.884] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:21:23,031.031] _internal.py -> _log line:96 [INFO]: 127.0.0.1 - - [30/Sep/2024 20:21:23] "POST /datasets/f3f28f75-8e60-4eba-b6df-4d1b390bbd89/documents HTTP/1.1" 200 -
[2024-09-30 20:40:23,502.502] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:40:23,807.807] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:40:27,359.359] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:40:27,362.362] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:40:31,085.085] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:40:31,394.394] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:40:41,919.919] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:40:45,362.362] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:40:45,365.365] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:41:46,817.817] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:41:47,077.077] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:41:50,686.686] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:41:50,689.689] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:54:14,004.004] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:54:14,323.323] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:54:18,388.388] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:54:22,527.527] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:54:30,973.973] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:54:35,114.114] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:54:38,220.220] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:54:38,222.222] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:54:41,970.970] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:54:42,257.257] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:54:45,570.570] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:54:45,573.573] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:54:48,191.191] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:54:48,488.488] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:55:00,591.591] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:55:03,788.788] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:55:03,791.791] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 20:55:07,458.458] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 20:55:07,846.846] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 20:55:11,873.873] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 20:55:11,876.876] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 23:33:36,102.102] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 23:33:36,418.418] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 23:33:40,201.201] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 23:33:40,204.204] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 23:33:40,499.499] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 23:33:40,773.773] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 23:33:43,924.924] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 23:33:43,927.927] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 23:33:45,360.360] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 23:33:45,620.620] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 23:33:48,299.299] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 23:33:48,302.302] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 23:34:27,711.711] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 23:34:28,024.024] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 23:34:31,111.111] _internal.py -> _log line:96 [WARNING]:  * Debugger is active!
[2024-09-30 23:34:31,113.113] _internal.py -> _log line:96 [INFO]:  * Debugger PIN: 102-324-223
[2024-09-30 23:34:32,545.545] _internal.py -> _log line:96 [INFO]:  * Detected change in 'D:\\Code\\llmops\\llmops-api\\internal\\schema\\document_schema.py', reloading
[2024-09-30 23:34:32,934.934] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 23:34:38,138.138] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 23:35:01,513.513] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 23:35:07,751.751] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 23:35:17,399.399] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
[2024-09-30 23:35:27,196.196] _internal.py -> _log line:96 [INFO]:  * Restarting with stat
